import dns from "node:dns";
dns.setServers(['8.8.8.8','8.8.4.4']);
import { Outfit } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/NavBar";
import Footer from "@/components/shared/Footer";

const outfit = Outfit({
  
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={` h-full antialiased`}
    >
      <body className={`${outfit.className} min-h-full flex flex-col`} >
        <NavBar/>
      <main>
          {children}
      </main>
      <Footer/>
        </body>
    </html>
  );
}
